from .bulk_templates import GENERATE_BULK_TEMPLATES_PROMPT
from .targeted_templates import GENERATE_TARGETED_TEMPLATES_PROMPT
from .targeted_facets import GENERATE_TARGETED_FACETS_PROMPT

__all__ = [
    "GENERATE_BULK_TEMPLATES_PROMPT",
    "GENERATE_TARGETED_TEMPLATES_PROMPT",
    "GENERATE_TARGETED_FACETS_PROMPT",
]
