name: evaluation

on:
  pull_request:
    types: [labeled]

jobs:
  trigger-eval:
    if: github.event.label.name == 'ci:eval'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Google Auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Submit Cloud Build
        run: |
          TAG_NAME="context-engineering-agent-pr-${{ github.event.pull_request.number }}-${GITHUB_SHA:0:7}"
          gcloud builds submit \
            --config .ci/cloudbuild.yaml \
            --substitutions TAG_NAME=$TAG_NAME,_PROJECT_LOCATION=us-central1 \
            .
